model:
  provider: "ollama"
  name: "codellama:7b-instruct"   
  temperature: 0.4
  max_tokens: 800

retrieval:
  chunk_size: 800
  chunk_overlap: 120
  top_k: 5

embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

classification:
  labels: ["basico", "intermedio", "avanzado"]
  test_size: 0.2
  random_state: 42
